 # Nama artefak yang akan diunduh. Jika tidak ditentukan, semua artefak untuk proses tersebut akan diunduh.
    nama: # opsional
    # Jalur tujuan. Mendukung perluasan tilde dasar. Defaultnya adalah $GITHUB_WORKSPACE
    jalur: # opsional
    # Pola glob yang cocok dengan artefak yang harus diunduh. Diabaikan jika nama ditentukan.
    pola: # opsional
    # Bila beberapa artefak dicocokkan, ini akan mengubah perilaku direktori tujuan. Jika benar, artefak yang diunduh akan berada di direktori yang sama yang ditentukan oleh jalur. Jika salah, artefak yang diunduh akan diekstrak ke direktori bernama individual dalam jalur yang ditentukan.
    merge-multiple: # opsional, defaultnya salah
    # Token GitHub yang digunakan untuk mengautentikasi dengan API GitHub. Ini diperlukan saat mengunduh artefak dari repositori lain atau dari alur kerja yang berbeda. Jika ini tidak ditentukan, tindakan akan mencoba mengunduh artefak dari repositori saat ini dan alur kerja saat ini.
    github-token: # opsional
    # Pemilik repositori dan nama repositori digabungkan dengan "/". Jika github-token ditentukan, ini adalah repositori tempat artefak akan diunduh.
    repositori: # opsional, defaultnya adalah ${{ github.repository }}
    # ID alur kerja tempat artefak unduhan yang diinginkan diunggah. Jika github-token ditentukan, ini adalah alur kerja tempat artefak akan diunduh.
    run-id: # opsional, defaultnya adalah ${{ github.run_id }}
